version: '3.1'

services:
  node:
    container_name: mstaff-micro__storybook__dev__node
    build: docker/dev
    working_dir: /application
    ports:
      - '23000:6006'
    volumes:
      - .:/application

networks:
  mstaff-micro.network:
    external: true